# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
