# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='codigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
