# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videojuegos', '0002_auto_20171121_0010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videojuego',
            options={'ordering': ('codigo',)},
        ),
    ]
